In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('hr_analytics/HR_comma_sep.csv')

In [9]:
df[['average_montly_hours','satisfaction_level']]

       average_montly_hours  satisfaction_level
0                       157                0.38
1                       262                0.80
2                       272                0.11
3                       223                0.72
4                       159                0.37
5                       153                0.41
6                       247                0.10
7                       259                0.92
8                       224                0.89
9                       142                0.42
10                      135                0.45
11                      305                0.11
12                      234                0.84
13                      148                0.41
14                      137                0.36
15                      143                0.38
16                      160                0.45
17                      255                0.78
18                      160                0.45
19                      262                0.76
20                      282                0.11
21                      147                0.38
22                      304                0.09
23                      139                0.46
24                      158                0.40
25                      242                0.89
26                      239                0.82
27                      135                0.40
28                      128                0.41
29                      132                0.38
...                     ...                 ...
14969                   157                0.43
14970                   225                0.78
14971                   140                0.39
14972                   310                0.11
14973                   143                0.36
14974                   153                0.36
14975                   310                0.10
14976                   136                0.40
14977                   251                0.81
14978                   144                0.40
14979                   296                0.09
14980                   238                0.76
14981                   162                0.73
14982                   137                0.38
14983                   257                0.72
14984                   148                0.40
14985                   254                0.91
14986                   247                0.85
14987                   206                0.90
14988                   145                0.46
14989                   159                0.43
14990                   228                0.89
14991                   257                0.09
14992                   155                0.40
14993                   293                0.76
14994                   151                0.40
14995                   160                0.37
14996                   143                0.37
14997                   280                0.11
14998                   158                0.37

[14999 rows x 2 columns]